# Project Metadata for Dracula London
# Version: 1

[project]
id = "260011-SP"
title = "Dracula London"

[client]
name = "Kindred Partners Ltd"
short_name = "KindredPartners"
address_line1 = "3rd Floor, Joel House, 17-19 Garrick Street"
address_line2 = "London WC2E 9AR, United Kingdom"

[client.contact]
salutation = "Mr"
title = ""
email = "martyn@martynsands.com"
phone = "+44 7791 122086"

[client.contact.name]
first = "Martyn"
last = "Sands"

[client.contact2]
salutation = "Ms"
title = ""
email = "amanda@kindred-partners.com"
phone = ""
company = "Kindred Partners International Ltd"

[client.contact2.name]
first = "Amanda"
last = "Murray"

[client.contact3]
salutation = "Mr"
title = ""
email = "stuart@tgrprods.com"
phone = ""
company = "TGR Productions"

[client.contact3.name]
first = "Stuart"
last = "Tucker"

[simplemotion]
entity = "SimpleMotion.Projects Pty Ltd"
short_name = "SimpleMotion"
abn = "67 126 272 197"
address_line1 = "20-22 Hampstead Rd"
address_line2 = "AUBURN NSW 2144, Australia"
phone = "+61 2 9046 1400"
website = "www.simplemotion.com"

[simplemotion.author]
name = "Greg Gowans"
pronouns = "he/him"
title = "Managing Director"
mobile = "+61 418 888 604"
email = "greg.gowans@simplemotion.com"
